### PR TITLE
Changed the value for the domain ..

### PR DESCRIPTION
**Pull request by atordvairn**
- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

### CODE REVIEW

**Review by willin — APPROVED** [review]

**Comment by atordvairn** [comment]
Screenshot_2022-02-04-15-18-35-820

**Comment by atordvairn** [comment]
haven't seen this one before.

**Comment by atordvairn** [comment]
Screenshot_2022-02-04-15-22-55-325
Everything seems fine..

**Comment by willin** [comment]
oh，you should not enable cdn. fixed

**Comment by atordvairn** [comment]
Please add theese as txt records for this domain 

`google-site-verification=f4WNAJMKgx26_UFgiD3rZqSfbPJD7NuxPIxJMWfOhRc`

**Comment by willin** [comment]
done

**Pull request merged**
